name: Build and deploy ASP app to Azure Web App - WebAppRun01

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Set up MSBuild for building .NET projects
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      # Set up NuGet for restoring packages
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      # Restore NuGet packages (ensure correct path to solution file)
      - name: Restore NuGet packages
        run: nuget restore MyAspApp/MyAspApp.sln

      # Build and publish the app to a folder (use dotnet publish if needed)
      - name: Build and publish the app
        run: msbuild MyAspApp/MyAspApp.sln /nologo /verbosity:m /t:Build /p:DeployOnBuild=true /p:PublishDir="published"

      # List contents of the published directory for debugging
      - name: List contents of published directory
        run: dir published

      # Upload the build artifact for deployment job
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: asp-net-app
          path: published/

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      # Download the artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: asp-net-app

      # Deploy the app to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'WebAppRun01'
          slot-name: 'Production'
          package: ./published
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E22207CD003849BA9D5F505DF3DE9681 }}
